### ISSUE TITLE
User rights

### ISSUE THREAD

**Issue by peykens** [StefanScherer/swarm-monitor#1]
Hi @StefanScherer,

I would like to to use your monitor to visualize my kubernetes apps.
My first step is to get your version working.

When I spin up your docker image, I can see in the logging the apps passing by, but the led's are not triggered.

How did you solve the user rights so the container has the rights to access the GPIO ?

Thx,
Peter

**Comment by StefanScherer** [comment]
Hi Peter,

Thanks for your interest. The way I use this image is described in the README.md running with HypriotOS and Docker 17.05. 

For Kubernetes you might find https://github.com/apprenda/blinkt-k8s-controller more useful.

**Comment by peykens** [comment]
HI Stefan,

Thx for the very quick response and the reference.
That's what i'm looking for.

Regards,
Peter

**Comment by StefanScherer** [comment]
Have fun and tweet a short video 😀

**Comment by mozzhead164** [comment]
Sorry I know this is an old (closed) issue but i am having the same problem as above.

I am running Raspbian buster latest on 5x raspberry pi 4 (4GB)
Docker version 19.03.6
The Blinkt modules have been tested with pimoroni test/example script 

I have scaled 4x apps with 5 tasks each (so 20 in total including monitor) and still I've got nothing on the LEDs :(

Added the monitor service to my docker-compose file as shown below;
```
####################################
##        Blinkt Monitor          ##
####################################
  monitor:
    image: stefanscherer/monitor:1.2.0
    deploy:
      mode: global
      restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 3
         window: 120s      
    volumes:
      - "/sys:/sys"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
What am i doing wrong? If you need anything more about my setup/config let me know!

Many thanks 

@StefanScherer... any thoughts?
